# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-24 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAssignmentModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensor_id', models.TextField(unique=True)),
                ('platform_id', models.TextField(unique=True)),
                ('assign_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformDeploymentModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('platform_id', models.TextField(unique=True)),
                ('platform_ip', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Deployment',
        ),
    ]
