influxsrv:
  image: "tutum/influxdb:latest"
  ports:
    - "8084:8083"
    - "8086:8086"
  expose:
    - "8090"
    - "8099"
  environment:
    - PRE_CREATE_DB=oneM2M
  container_name: indfluxDB

grafana:
  image: "grafana/grafana"
  ports:
    - "3000:3000"
    - "8000:80"
  environment:
    - INFLUXDB_HOST=localhost
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=oneM2M
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
    - GF_SERVER_ROOT_URL=http://grafana.server.name
    - GF_SECURITY_ADMIN_PASSWORD=secret
  links:
    - "influxsrv:influxsrv"
  container_name: grafana