---
- hosts: all  
  tasks:
   - name: Get Kubernetes Repo
     shell: git clone https://github.com/kubernetes/kube-deploy.git

- hosts: all  
  tasks:
   - name: Move to repo
     shell: cd kube-deploy/docker-multinode

   - name: Define master node
     shell: export MASTER_IP=192.168.30.42

   - name: Run worker node
     shell: sudo ./worker.sh
