apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-service
  namespace: cloud-kube-system
spec:
  type: NodePort
  ports:
  - port: 5672
  selector:
    app: taskQueue
    component: rabbitmq
