apiVersion: v1
kind: ReplicationController
metadata:
    name: onem2m
    namespace: kube-system
spec:
    replicas: 1
    selector:
      app: onem2m
    template:
      metadata:
        name: onem2m
        labels:
          app: onem2m
      spec:
        containers:
        - name: onem2m
          image: huanphan/onem2m:0.9
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: onem2m-config
            mountPath: /usr/src/ipe_config
          - name: onem2m-items
            mountPath: /usr/src/ipe_config
        volumes:
        - name: onem2m-config
          configMap:
            name: onem2m-config
            items:
            - key: config.cfg
              path: config.cfg
        - name: onem2m-items
          configMap:
            name: onem2m-items
            items:
            - key: items.cfg
              path: items.cfg
        restartPolicy: Always
