apiVersion: v1
kind: Service
metadata:
    name: mqtt-service
    namespace: cloud-kube-system
spec:
    type: NodePort
    selector:
      app: mqtt
    ports:
        - name: mqtt
          protocol: TCP
          port: 1883
        - name: websockermqtt
          protocol: TCP
          port: 9001

