apiVersion: v1
kind: ReplicationController
metadata:
    name: mqtt
spec:
    replicas: 1
    selector:
        app: mqtt
    template:
        metadata:
            name: mqtt
            labels:
                app: mqtt
        spec:
            containers:
            - name: mqtt
              image: toke/mosquitto
              ports:
              - containerPort: 1883
              - containerPort: 9001
