apiVersion: v1
kind: Service
metadata:
    name: mqtt-service
spec:
    selector:
      app: mqtt
    ports:
        - name: mqtt
          protocol: TCP
          port: 1883
        - name: websockermqtt
          protocol: TCP
          port: 9001

