apiVersion: v1
kind: ReplicationController
metadata:
    name: om2m
spec:
    replicas: 1
    selector: 
      app: om2m
    template:
      metadata:
        name: om2m
        labels:
          app: om2m
      spec:
        containers:
        - name: om2m
          image: huanphan/onem2m:fix_config
          ports:
          - containerPort: 8080
          volumeMounts:
          - name: ipe-config
            mountPath: /usr/src/workspace/src/main/resources
          command: ["/bin/sh","-c"]
          args: ["/bin/sh /usr/src/start-cse.sh; nohup /usr/src/start-mn-cse.sh "]
        volumes:
        - name: ipe-config
          configMap:
            name: om2m-ipe-config
