FROM python:3.4

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/
RUN pip install -r requirements.txt

COPY emit_data.py /usr/src/app

CMD [ "python3", "./emit_data.py" ]
