apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: measure-data-rate
  namespace: cloud-kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: measure
        app: measure-data-rate
    spec:
      containers:
      - name: measure-data-rate
        image: huanphan/measure-data-rate:0.1

